export const budgetCategories = [
  'Richie',
  'Stef',
  'Ben',
  'Clothes',
  'Groceries',
  'Entertainment',
  'Home Supplies',
  'Gifts',
  'Big Necessities',
  'Optional Important',
  'Travel',
  'Christmas',
  'Charity',
  'Richie Projects',
  'To be determined',
  'Work Expenses',
  'Gas',
  'Income',
  'Transfer',
  'Mortgage',
  'Student Loan',
  'Subscriptions',
  'Utilities',
];
