export const budgetCategories = [
  'Richie',
  'Stef',
  'Kids',
  'Clothes',
  'Groceries',
  'Entertainment',
  'Home Supplies',
  'Home repair and renovations',
  'Healthcare',
  'Car maintenance',
  'Petcare',
  'Gifts',
  'Big Necessities',
  'Optional Important',
  'Travel',
  'Christmas',
  'Charity',
  'Richie Projects',
  'To be determined',
  'Work Expenses',
  'Gas',
  'Income',
  'Transfer',
  'Mortgage',
  'Home insurance',
  'Car insurance',
  'Student Loan',
  'Subscriptions',
  'Utilities',
];
